### ISSUE TITLE
typoしてんで

### ISSUE THREAD

**Issue by Ran350** [Cork0158/calculater#1]
calculater -> calculator

- repository name
- [calculater/blob/main/calculater.js](https://github.com/Cork0158/calculater/blob/main/calculater.js)
- [README.md](https://github.com/Cork0158/calculater/blob/main/README.md)

**Comment by Ran350** [comment]
calculater -> calculator

- repository name
- [calculater/blob/main/calculater.js](https://github.com/Cork0158/calculater/blob/main/calculater.js)
- [README.md](https://github.com/Cork0158/calculater/blob/main/README.md)

**Comment by Cork0158** [comment]
typoはご愛嬌
